# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/louis-pro/MIRROR-B-OOP-400-NAN-4-1-raytracer-andreas.le-tanter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/louis-pro/MIRROR-B-OOP-400-NAN-4-1-raytracer-andreas.le-tanter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis-pro/MIRROR-B-OOP-400-NAN-4-1-raytracer-andreas.le-tanter/CMakeFiles /home/louis-pro/MIRROR-B-OOP-400-NAN-4-1-raytracer-andreas.le-tanter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis-pro/MIRROR-B-OOP-400-NAN-4-1-raytracer-andreas.le-tanter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named tests_run

# Build rule for target.
tests_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests_run
.PHONY : tests_run

# fast build rule for target.
tests_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_run.dir/build.make CMakeFiles/tests_run.dir/build
.PHONY : tests_run/fast

src/Factory/Factory.o: src/Factory/Factory.cpp.o
.PHONY : src/Factory/Factory.o

# target to build an object file
src/Factory/Factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Factory/Factory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Factory/Factory.cpp.o
.PHONY : src/Factory/Factory.cpp.o

src/Factory/Factory.i: src/Factory/Factory.cpp.i
.PHONY : src/Factory/Factory.i

# target to preprocess a source file
src/Factory/Factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Factory/Factory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Factory/Factory.cpp.i
.PHONY : src/Factory/Factory.cpp.i

src/Factory/Factory.s: src/Factory/Factory.cpp.s
.PHONY : src/Factory/Factory.s

# target to generate assembly for a file
src/Factory/Factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Factory/Factory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Factory/Factory.cpp.s
.PHONY : src/Factory/Factory.cpp.s

src/Math/Point3D/Point3D.o: src/Math/Point3D/Point3D.cpp.o
.PHONY : src/Math/Point3D/Point3D.o

# target to build an object file
src/Math/Point3D/Point3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Math/Point3D/Point3D.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Math/Point3D/Point3D.cpp.o
.PHONY : src/Math/Point3D/Point3D.cpp.o

src/Math/Point3D/Point3D.i: src/Math/Point3D/Point3D.cpp.i
.PHONY : src/Math/Point3D/Point3D.i

# target to preprocess a source file
src/Math/Point3D/Point3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Math/Point3D/Point3D.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Math/Point3D/Point3D.cpp.i
.PHONY : src/Math/Point3D/Point3D.cpp.i

src/Math/Point3D/Point3D.s: src/Math/Point3D/Point3D.cpp.s
.PHONY : src/Math/Point3D/Point3D.s

# target to generate assembly for a file
src/Math/Point3D/Point3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Math/Point3D/Point3D.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Math/Point3D/Point3D.cpp.s
.PHONY : src/Math/Point3D/Point3D.cpp.s

src/Math/Vector3D/Vector3D.o: src/Math/Vector3D/Vector3D.cpp.o
.PHONY : src/Math/Vector3D/Vector3D.o

# target to build an object file
src/Math/Vector3D/Vector3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Math/Vector3D/Vector3D.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Math/Vector3D/Vector3D.cpp.o
.PHONY : src/Math/Vector3D/Vector3D.cpp.o

src/Math/Vector3D/Vector3D.i: src/Math/Vector3D/Vector3D.cpp.i
.PHONY : src/Math/Vector3D/Vector3D.i

# target to preprocess a source file
src/Math/Vector3D/Vector3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Math/Vector3D/Vector3D.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Math/Vector3D/Vector3D.cpp.i
.PHONY : src/Math/Vector3D/Vector3D.cpp.i

src/Math/Vector3D/Vector3D.s: src/Math/Vector3D/Vector3D.cpp.s
.PHONY : src/Math/Vector3D/Vector3D.s

# target to generate assembly for a file
src/Math/Vector3D/Vector3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Math/Vector3D/Vector3D.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Math/Vector3D/Vector3D.cpp.s
.PHONY : src/Math/Vector3D/Vector3D.cpp.s

src/Parser/Parser.o: src/Parser/Parser.cpp.o
.PHONY : src/Parser/Parser.o

# target to build an object file
src/Parser/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Parser/Parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Parser/Parser.cpp.o
.PHONY : src/Parser/Parser.cpp.o

src/Parser/Parser.i: src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.i

# target to preprocess a source file
src/Parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Parser/Parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.cpp.i

src/Parser/Parser.s: src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.s

# target to generate assembly for a file
src/Parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Parser/Parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.cpp.s

src/RayTracer/Camera/Camera.o: src/RayTracer/Camera/Camera.cpp.o
.PHONY : src/RayTracer/Camera/Camera.o

# target to build an object file
src/RayTracer/Camera/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Camera/Camera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Camera/Camera.cpp.o
.PHONY : src/RayTracer/Camera/Camera.cpp.o

src/RayTracer/Camera/Camera.i: src/RayTracer/Camera/Camera.cpp.i
.PHONY : src/RayTracer/Camera/Camera.i

# target to preprocess a source file
src/RayTracer/Camera/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Camera/Camera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Camera/Camera.cpp.i
.PHONY : src/RayTracer/Camera/Camera.cpp.i

src/RayTracer/Camera/Camera.s: src/RayTracer/Camera/Camera.cpp.s
.PHONY : src/RayTracer/Camera/Camera.s

# target to generate assembly for a file
src/RayTracer/Camera/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Camera/Camera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Camera/Camera.cpp.s
.PHONY : src/RayTracer/Camera/Camera.cpp.s

src/RayTracer/Objects/Sphere/Sphere.o: src/RayTracer/Objects/Sphere/Sphere.cpp.o
.PHONY : src/RayTracer/Objects/Sphere/Sphere.o

# target to build an object file
src/RayTracer/Objects/Sphere/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Objects/Sphere/Sphere.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Objects/Sphere/Sphere.cpp.o
.PHONY : src/RayTracer/Objects/Sphere/Sphere.cpp.o

src/RayTracer/Objects/Sphere/Sphere.i: src/RayTracer/Objects/Sphere/Sphere.cpp.i
.PHONY : src/RayTracer/Objects/Sphere/Sphere.i

# target to preprocess a source file
src/RayTracer/Objects/Sphere/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Objects/Sphere/Sphere.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Objects/Sphere/Sphere.cpp.i
.PHONY : src/RayTracer/Objects/Sphere/Sphere.cpp.i

src/RayTracer/Objects/Sphere/Sphere.s: src/RayTracer/Objects/Sphere/Sphere.cpp.s
.PHONY : src/RayTracer/Objects/Sphere/Sphere.s

# target to generate assembly for a file
src/RayTracer/Objects/Sphere/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Objects/Sphere/Sphere.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Objects/Sphere/Sphere.cpp.s
.PHONY : src/RayTracer/Objects/Sphere/Sphere.cpp.s

src/RayTracer/Ray/Ray.o: src/RayTracer/Ray/Ray.cpp.o
.PHONY : src/RayTracer/Ray/Ray.o

# target to build an object file
src/RayTracer/Ray/Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Ray/Ray.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Ray/Ray.cpp.o
.PHONY : src/RayTracer/Ray/Ray.cpp.o

src/RayTracer/Ray/Ray.i: src/RayTracer/Ray/Ray.cpp.i
.PHONY : src/RayTracer/Ray/Ray.i

# target to preprocess a source file
src/RayTracer/Ray/Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Ray/Ray.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Ray/Ray.cpp.i
.PHONY : src/RayTracer/Ray/Ray.cpp.i

src/RayTracer/Ray/Ray.s: src/RayTracer/Ray/Ray.cpp.s
.PHONY : src/RayTracer/Ray/Ray.s

# target to generate assembly for a file
src/RayTracer/Ray/Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Ray/Ray.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Ray/Ray.cpp.s
.PHONY : src/RayTracer/Ray/Ray.cpp.s

src/RayTracer/Renderer/Renderer.o: src/RayTracer/Renderer/Renderer.cpp.o
.PHONY : src/RayTracer/Renderer/Renderer.o

# target to build an object file
src/RayTracer/Renderer/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Renderer/Renderer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Renderer/Renderer.cpp.o
.PHONY : src/RayTracer/Renderer/Renderer.cpp.o

src/RayTracer/Renderer/Renderer.i: src/RayTracer/Renderer/Renderer.cpp.i
.PHONY : src/RayTracer/Renderer/Renderer.i

# target to preprocess a source file
src/RayTracer/Renderer/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Renderer/Renderer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Renderer/Renderer.cpp.i
.PHONY : src/RayTracer/Renderer/Renderer.cpp.i

src/RayTracer/Renderer/Renderer.s: src/RayTracer/Renderer/Renderer.cpp.s
.PHONY : src/RayTracer/Renderer/Renderer.s

# target to generate assembly for a file
src/RayTracer/Renderer/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/RayTracer/Renderer/Renderer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/RayTracer/Renderer/Renderer.cpp.s
.PHONY : src/RayTracer/Renderer/Renderer.cpp.s

src/Rectangle3D.o: src/Rectangle3D.cpp.o
.PHONY : src/Rectangle3D.o

# target to build an object file
src/Rectangle3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Rectangle3D.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Rectangle3D.cpp.o
.PHONY : src/Rectangle3D.cpp.o

src/Rectangle3D.i: src/Rectangle3D.cpp.i
.PHONY : src/Rectangle3D.i

# target to preprocess a source file
src/Rectangle3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Rectangle3D.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Rectangle3D.cpp.i
.PHONY : src/Rectangle3D.cpp.i

src/Rectangle3D.s: src/Rectangle3D.cpp.s
.PHONY : src/Rectangle3D.s

# target to generate assembly for a file
src/Rectangle3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Rectangle3D.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Rectangle3D.cpp.s
.PHONY : src/Rectangle3D.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fclean"
	@echo "... re"
	@echo "... tests_run"
	@echo "... raytracer"
	@echo "... unit_tests"
	@echo "... src/Factory/Factory.o"
	@echo "... src/Factory/Factory.i"
	@echo "... src/Factory/Factory.s"
	@echo "... src/Math/Point3D/Point3D.o"
	@echo "... src/Math/Point3D/Point3D.i"
	@echo "... src/Math/Point3D/Point3D.s"
	@echo "... src/Math/Vector3D/Vector3D.o"
	@echo "... src/Math/Vector3D/Vector3D.i"
	@echo "... src/Math/Vector3D/Vector3D.s"
	@echo "... src/Parser/Parser.o"
	@echo "... src/Parser/Parser.i"
	@echo "... src/Parser/Parser.s"
	@echo "... src/RayTracer/Camera/Camera.o"
	@echo "... src/RayTracer/Camera/Camera.i"
	@echo "... src/RayTracer/Camera/Camera.s"
	@echo "... src/RayTracer/Objects/Sphere/Sphere.o"
	@echo "... src/RayTracer/Objects/Sphere/Sphere.i"
	@echo "... src/RayTracer/Objects/Sphere/Sphere.s"
	@echo "... src/RayTracer/Ray/Ray.o"
	@echo "... src/RayTracer/Ray/Ray.i"
	@echo "... src/RayTracer/Ray/Ray.s"
	@echo "... src/RayTracer/Renderer/Renderer.o"
	@echo "... src/RayTracer/Renderer/Renderer.i"
	@echo "... src/RayTracer/Renderer/Renderer.s"
	@echo "... src/Rectangle3D.o"
	@echo "... src/Rectangle3D.i"
	@echo "... src/Rectangle3D.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

