name: chocolatine
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-OOP-400-NAN-4-1-raytracer-andreas.le-tanter.git
  EXECUTABLE: "raytracer"
  UNWANTED_FILES: '^(.*\/)*((.*\.(([ao])|(so)|(gcno)|(gcda)|(gcov)))|(^.*\~)|(.*\/tmp\/.+)|(#.*\#))$'

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.check_unwanted_files.outputs.summary }}
      result: ${{ steps.check_unwanted_files.outputs.result }}
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: check_unwanted_files
        name: Check unwanted files
        run: |
          echo "summary=| Check unwanted files " >> $GITHUB_OUTPUT
          error=0
          for file in $(git ls-files); do
            if [[ $file =~ $UNWANTED_FILES ]]; then
              echo "::error title=Unwanted file detected::File $file is not allowed in the repository."
              error=1
            fi
          done
          if [ $error -eq 1 ]; then
            echo "result=| :x: |" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: [check_repository_cleanliness]
    outputs:
      summary: ${{ steps.check_if_executable_exists.outputs.summary }}
      result: ${{ steps.check_if_executable_exists.outputs.result }}
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install libconfig-dev
        run: |
          sudo apt-get install -y libconfig-dev
      - name: Build project
        run: |
          cmake .
      - name: Compile project
        run: |
          make
      - id: check_if_executable_exists
        name: Check if executable exists
        run: |
          echo "summary=| Check if executable exists " >> $GITHUB_OUTPUT
          if [ -f $EXECUTABLE ]; then
            echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT
          else
            echo "::error title=Executable not found::The executable $EXECUTABLE was not found."
            echo "result=| :x: |" >> $GITHUB_OUTPUT
            exit 1
          fi

  run_units_tests:
    runs-on: ubuntu-latest
    needs: [check_repository_cleanliness]
    outputs:
      summary: ${{ steps.check_if_unit_tests_exists.outputs.summary }}
      result: ${{ steps.check_if_unit_tests_exists.outputs.result}}
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install libconfig-dev
        run: |
          sudo apt-get install -y libconfig-dev
      - name: Build project
        run: |
          cmake .
      - id: check_if_unit_tests_exists
        name: Compile and run unit tests
        run: |
          echo "summary=| Compile and run unit tests " >> $GITHUB_OUTPUT
          make tests_run
          if [ $? -eq 0 ]; then
            echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT
          else
            echo "::error title=Unit tests failed::The unit tests failed."
            echo "result=| :x: |" >> $GITHUB_OUTPUT
            exit 1
          fi

  run_functionals_tests:
    runs-on: ubuntu-latest
    needs: [check_repository_cleanliness]
    outputs:
      summary: ${{ steps.run_functionals_tests.outputs.summary }}
      result: ${{ steps.run_functionals_tests.outputs.result }}
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name : Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install libconfig-dev
        run: |
          sudo apt-get install -y libconfig-dev
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Atomot/ftest
      - name: Build project
        run: |
          echo "cmake CMakeLists.txt"
      - name: Compile functionals tests
        run: |
          echo "make functinals_tests_run"
      - id: run_functionals_tests
        name: Run functinals tests
        run: |
          wget "https://github.com/Atomot/ftest/releases/download/v0.1.0/ftest" -O ftest
          chmod +x ftest
          echo "summary=| Run functinals tests " >> $GITHUB_OUTPUT
          echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT

  create_doxygen:
    runs-on: ubuntu-latest
    needs: [check_program_compilation, run_units_tests, run_functionals_tests]
    outputs:
      summary: ${{ steps.create_doxygen.outputs.summary }}
      result: ${{ steps.create_doxygen.outputs.result }}
    steps:
      - name : Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install doxygen
        run: |
          sudo apt-get install -y doxygen
      - name: Create doxygen
        run: |
          doxygen Doxyfile
      - id: create_doxygen
        name: Add doxygen to release
        run: |
          echo "summary=| Create doxygen " >> $GITHUB_OUTPUT
          echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT

  print_summary:
    runs-on: ubuntu-latest
    needs: [check_repository_cleanliness, check_program_compilation, run_units_tests, run_functionals_tests, create_doxygen]
    env:
      check_repository_cleanliness: ${{ needs.check_repository_cleanliness.outputs.summary }}
      check_repository_cleanliness_result: ${{ needs.check_repository_cleanliness.outputs.result }}
      check_program_compilation: ${{ needs.check_program_compilation.outputs.summary }}
      check_program_compilation_result: ${{ needs.check_program_compilation.outputs.result }}
      run_units_tests: ${{ needs.run_units_tests.outputs.summary }}
      run_units_tests_result: ${{ needs.run_units_tests.outputs.result }}
      run_functionals_tests: ${{ needs.run_functionals_tests.outputs.summary }}
      run_functionals_tests_result: ${{ needs.run_functionals_tests.outputs.result }}
      create_doxygen: ${{ needs.create_doxygen.outputs.summary }}
      create_doxygen_result: ${{ needs.create_doxygen.outputs.result }}
    steps:
      - name: Print summary
        run: |
          echo "## Summary of the workflow :rocket:"
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| ---- | ------ |" >> $GITHUB_STEP_SUMMARY
          echo "$check_repository_cleanliness $check_repository_cleanliness_result" >> $GITHUB_STEP_SUMMARY
          echo "$check_program_compilation $check_program_compilation_result" >> $GITHUB_STEP_SUMMARY
          echo "$run_units_tests $run_units_tests_result" >> $GITHUB_STEP_SUMMARY
          echo "$run_functionals_tests $run_functionals_tests_result" >> $GITHUB_STEP_SUMMARY
          echo "$create_doxygen $create_doxygen_result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY


  push_to_mirror:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [create_doxygen]
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
